title: Kihyo Park
logo: /assets/img/me.png
description: 박기효 [pak̚.g̊i.ço]
show_downloads: true
url: "https://kihyo-park.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics:
theme: jekyll-theme-minimal
